### ISSUE TITLE
Script ran too long

### ISSUE THREAD

**Issue by Pariah** [Gunnydelight/mozzGitHub#48]
First of all, thank you for this group. It's proved very useful. I do have an issue however.

Anytime I go to add most (not all) of the old content groups, I receive a LUA error of "script ran too long" for TradeSkillMaster\Core\Service\Groups\Core.lua:369

I have tried importing them with TSM being the only addon enabled and have received the same error. I have also tried importing without operations and removing many items but to no avail.

I was wondering if you would perhaps have a solution or if you're able to at least repeat the same error on a new profile to see whether it's just me or the import size is in fact just too large.

Thank you for your time!

**Comment by Braintelligence** [comment]
I only had problems importing the old raw mats.

**Comment by Pariah** [comment]
Interesting. I'm wondering what else I could possibly do to import them. Thank you for your response however. Any insight is useful.

**Comment by Braintelligence** [comment]
I reloaded and reran the import until it went through completely. I could import everything this way. I guess only part of the import makes it into the system each run for big import strings.

**Comment by Pariah** [comment]
Oh, that's clever. I'll give it a try. Thank you again for your help, mate.

**Comment by Gunnydelight** [comment]
Hey catching up on this website to get it to where I want to be. What script are you referencing, a personal script?

**Comment by Pariah** [comment]
I was referencing a couple of your own scripts. A few of them were quite large so I was having issues importing them. But I took Braintelligence's advice and just repeatedly importing the same one seemed to have solved the issue.

**Comment by Gunnydelight** [comment]
Alright - gracias senior. Most likely due to the size the import. If its consistent, can explore ways to chunk it down
